ALTER TABLE users
    ADD COLUMN IF NOT EXISTS mbti_type VARCHAR(4),
    ADD COLUMN IF NOT EXISTS mbti_taken_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS mi_scores_json TEXT,
    ADD COLUMN IF NOT EXISTS mi_taken_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS personality_public BOOLEAN DEFAULT FALSE;
