# Copy this file to application-secret.properties for local development only.
# Do not commit application-secret.properties.
cloudinary.cloud-name=dgny2gq8p
cloudinary.api-key=272876721693681
cloudinary.api-secret=XpaRcGf2TJxnCDuiUBccvFYF_wM
spring.mail.username=your_email@example.com
spring.mail.password=your_email_app_password
ttjobs.email.from=your_email@example.com
